---
title: "Homework 5"
author: "Fangyi Chen"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---


```{r load_libraries}
library(tidyverse)
library(ggridges)
library(rvest)
library(broom)

```



## Problem 2
```{r data loading & preprocessing}
file_names = list.files("data")

combined_df = map_df(file_names, ~{
  df = read_csv(file.path("data", .x), show_col_types = FALSE)
  
  subject_id = str_extract(.x, "\\d+")
  
  arm = str_extract(.x, "(con|exp)")
  
  df |> 
    mutate(subject_id = subject_id,
           arm = arm) |> 
    select(subject_id, arm, everything())
  
})

```


```{r spaghetti plot}

combined_df |> 
      pivot_longer(week_1:week_8,
                 names_to = "week",
                 names_prefix = "week_" ,
                 values_to = "observation") |> 
  ggplot(aes(x=week,y= observation, group=subject_id, color=arm)) +
  geom_line() + 
  facet_grid(. ~arm) +
  labs(title = "Spaghetti Plot of Observations Over Time",
       x = "Week",
       y = "Observation") 

```
### Comments: In the experiment arm , we did perceive a increasing trend from week 1 to week8, whereas for control group, there appears to have difference between week1 and week8 in the end. 

## Problem 3
```{r}
set.seed(1)

list_mu = c (0, 1, 2, 3, 4, 5)

gather_test_results = function(mu) {

  n = 30
  sigma = 5
  alpha = 0.05
  
  simulated_data = replicate(5000, rnorm(n=n, mean=mu, sd=sigma))
  
  test_results = map_dfr(simulated_data, ~tidy(t.test(.x, mu=0)))
  
  power_results = mean(test_results$p.value < 0.05)
  
  avg_mu = mean(test_results$estimate)
  
  avg_mu_reject = mean(test_results[test_results$p.value < 0.05]$estimate)
  
  return(tibble(
    true_mu = mu,
    power_results = power_results,
    avg_mu = avg_mu,
    avg_mu_reject = avg_mu_reject
  ))
}


```

